// In-game short bios for the 30 base species (full versions + per-body-type themes
// in docs/BESTIARY.md). Kept condensed; the long-form doc is the canonical lore.
export const BIOS: Record<string, string> = {
  // --- Mammal: displacement & renewed purpose ---
  kongrath: 'Grew up the biggest, quietest member of a wandering troupe of smaller, mismatched creatures who banded together for safety on the road. He never asked to be their protector — he was just the one nothing dared approach twice. When the troupe finally scattered, he found he missed having something worth standing between, and joined the Circuit looking for the same thing all over again.',
  aegisox: 'A retired guardian of a mountain caravan road, left obsolete when the caravans traded oxen for engines. She brought her unbreakable stance to the arena, where a wall still has worth, and fights to shield her teammates more than to win.',
  maneleo: 'Deposed from his pride by a younger challenger and refusing exile, he joined the Circuit to rebuild his name from nothing and gather a new pride — teammates who will stand and roar at his side.',
  grivvel: 'His frostwoods territory shrank a little more every winter — warmer seasons, hungrier rivals, a logging road through his old range — until the wild simply left him behind. The Circuit is the first place in years with honest, deliberate boundaries, and he is already picking the next fight before the last one has cooled.',
  ursath: 'Woke from a long hibernation to find his forest felled and paved. He wanders the Circuit half in search of a new home, half for the honest satisfaction of a Titan’s Maul landing true.',
  // --- Avian: scarcity, migration, and the long way back ---
  skyrend: 'Born mid-migration, in a generation that never saw the ancestral cliffs her parents fled when the hunting grounds dried up. Word has finally reached the flock that the old cliffs are green again, and she is testing every wingbeat of the long flight home on the Circuit.',
  strixil: 'Stayed behind when drought scattered her flock, keeping the old roost’s knowledge alive for whoever eventually found their way back. Now the flock trickles home in twos and threes, and she has become the archivist they all quietly rely on.',
  zephyri: 'Hatched during the worst of the scattering and never really stopped moving since — while the flock finally resettles the recovered roosts, she has discovered she does not want to. The crowd’s gasp as she blurs untouched through a Thousand Cuts is the only homecoming she wants.',
  corvaan: 'Learned to make a home out of nowhere in particular during the long scattering, picking up trinkets and a stolen spellbook from every territory the flock blew through. Now that the old roost calls everyone back, he finds he would rather collect reputation than a nest.',
  larkessa: 'Her voice became more than talent during the scattering — flung far enough on the wind, it helped separated flockmates find each other across a continent of empty sky. The roost is full again, and the applause still reminds her that every one of those voices made it home.',
  // --- Marsupial: the itinerant fair ---
  bruxaroo: 'Made his name in staged fairground exhibition bouts and grew tired of the choreography. He came to the Circuit hungry for real competition and the honest thud of an unrehearsed Knockout Combo.',
  koalio: 'Has traveled with more fairground troupes than he can name, a familiar stranger wherever the fair sets up next once the brush country turns too dry to stay put. He competes to prove gentleness can win — he would genuinely rather sing an opponent into a peaceful Dreamsong than strike them.',
  quokkade: 'The fair circuit’s most relentlessly cheerful competitor. She fights for the crowds and the friendships, and throws the same Festival in whatever field the troupe has pitched camp.',
  sylvaglide: 'Grew up the smallest member of a fair too used to moving fast to wait for stragglers, and learned early that the only way to keep up was to fly. She has spent her whole career turning being underestimated into an ambush.',
  tazzik: 'Every fair he has traveled with learns to read the signs and start packing a little early. The arena is the only place that can absorb his full Tasmanian Fury, and he is fiercely, secretly loyal to anyone who can weather it and grin back.',
  // --- Aquatic: the deep stirs ---
  maelurk: 'One of the first to feel the old trenches stir, and unlike most of his kind he swam toward the strangeness instead of away from it. He surfaced out of pure curiosity, treating each Abyssal Grasp as an experiment he is enjoying immensely.',
  nautilux: 'A thousand-tide drifter who has weathered every storm, including whatever is moving in the deep dark now. She competes not to conquer but to endure, taking slow, deep pride in being the Pearl Barrier no storm has ever broken.',
  serapelle: 'Surfaced long before anyone spoke of the trenches stirring, and has watched entire leagues rise and crumble since. He returns each season to mentor the young monsters now following him up from the dark, and to remind an impatient Circuit that patience outlasts power.',
  voltaray: 'One of the first in the deep to feel the stirring, and unlike his kin he chased the feeling up instead of retreating from it. He is a showman, hooked on the collective gasp of a crowd the instant his Thunderstorm lands.',
  corallux: 'Grown from a single surviving fragment of a bleached, dying reef — one small piece of the same deep unsettling stirring everything below the waves. He fights to carry that lost home’s name back into the light, every Reef Blade swung in its memory.',
  // --- Insectoid: decline & new nests ---
  scarabrute: 'Spent a century as the keystone of a dam his colony built, holding back a river with his own shell. When the colony finished their work and moved on, he found the Circuit — the only place left where something is allowed to hit him as hard as the river did.',
  mantevoke: 'Guardian of a temple garden fewer visitors bother to find anymore, and perhaps one of the last of his line still holding the old discipline. He competes to test whether that discipline still means anything in a world that has stopped watching.',
  arachnyx: 'Has never once left her lair to fight — opponents are escorted in. Reports of new webs appearing in territories long empty have left her, for the first time, curious about the wider insectoid world instead of dismissive of it.',
  vespera: 'A queen whose hive grew so vast and self-sufficient it no longer needed her orders — exactly the kind of new order the old colonies are quietly giving way to. She entered the Circuit to feel needed again, and ten thousand loyal wings follow her into every arena anyway.',
  odonatra: 'Hatched in one of the new nests quietly appearing where the old insectoid territories fell empty — young, fast, and utterly unbothered by whatever came before her. She flew through a tournament grounds by accident, dodged everything thrown at her on the way out, and came back the next season to do it on purpose.',
  // --- Reptilian: the long wait ends ---
  crocmaw: 'Waited motionless in his river for so long that maps marked him as a sandbar. The Circuit is the first thing in decades that made him move — and the arena floor still shakes when he does.',
  iguanor: 'Deposed no one, conquered nothing — a warband simply formed around him because he looks magnificent on a sun-warmed rock, and then it waited, for years, doing nothing in particular. He competes to finally prove the crown he never asked for was deserved.',
  serpwyn: 'An oracle who read the futures of champions for forty seasons before deciding to test whether prophecy is easier from inside the arena. She has never been surprised by an opponent. Not once.',
  geckari: 'Grew up scaling the arena’s outer walls for years to watch matches for free, long before he had a way in. Fights the way he watched — from angles nobody thinks to defend.',
  tortavos: 'He signed up for the Circuit two hundred years ago and arrived last spring, entirely unbothered. Time moves differently inside his shell, and opponents who rush him tend to find that out the hard way.',
}
