// Per-species, per-stage pixel-art sprites (§8, unique-sprite roadmap item).
// Starting with Mammals (user spec 2026-07-24, redesigned 2026-07-24 after
// user feedback that the first pass didn't read as the actual animals):
// each species gets its own 24x24 silhouette AND its own real colour
// palette (not a hue-rotated shared template) so the animal is identifiable
// by shape AND colour — a lion is gold with a mane, an ox is brown with pale
// horns, a gorilla is black with a silver back, a wolverine is dark with a
// light side-stripe, a bear is brown and stocky.
//
// Only the ADULT shape is hand-drawn per species. 'child' and 'teen' are the
// SAME silhouette scaled down toward the canvas centre (nearest-neighbour),
// not independently redrawn — guarantees every stage still reads as the
// same animal, just smaller, growing to full size/detail by adult like an
// evolution line. 'elder' is not stored here at all: Sprite.tsx reuses the
// adult grid with a desaturated/dimmed filter for the aged look.
// Legend: '.' transparent · X outline · B body · L belly/light · A accent
// (horns/mane/stripe/silverback, varies per species) · E eye · P pupil.

export type LifeStage = 'child' | 'teen' | 'adult'

export const SPRITE_SIZE = 24

export const SPECIES_SPRITES: Partial<Record<string, Record<LifeStage, string[]>>> = {
  kongrath: {
    child: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '..........BBBX..........',
      '.........XBPBPX.........',
      '.........XAAAA..........',
      '........XBXXXXBBX.......',
      '.......BBBLLLLLXBB......',
      '.......BBBBBBBBXBB......',
      '.......BBBXXXXXXBB......',
      '.......AAA......AA......',
      '........BBX..BBX........',
      '........BBX..BBX........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teen: [
      '........................',
      '........................',
      '........................',
      '..........XXXX..........',
      '........XXXXXXXX........',
      '........XBEPBEPB........',
      '........XBBBBBBX........',
      '.......XXBBBBBBBXX......',
      '......XBBBXXXXXXBBX.....',
      '.....XBBBBXXXXXXXBBBB...',
      '....XBBBBXLLLLLLLXBBB...',
      '....XBBBBXBBBBBBBXBBB...',
      '....XBBBBXBBBBBBBXBBB...',
      '....XBBBB.........BBB...',
      '....XAAAA.........AAA...',
      '.....XXXXX....XXXXX.....',
      '......XBBB...XBBBX......',
      '......XBBB...XBBBX......',
      '......XXXX...XXXXX......',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    adult: [
      '.........XXXXXX.........',
      '........XBBBBBBX........',
      '.......XXXXXXXXXX.......',
      '.......XBBEPBBEPBX......',
      '.......XBBBBBBBBX.......',
      '.......XAAAAAAAAX.......',
      '......XXBBBBBBBBBBXX....',
      '....XXBBBXXXXXXXXBBBXX..',
      '...XBBBBBXXXXXXXXXXBBBBB',
      '..XBBBBBXLLLLLLLLLLXBBBB',
      '..XBBBBBXLLLLLLLLLLXBBBB',
      '..XBBBBBXBBBBBBBBBBXBBBB',
      '..XBBBBBXBBBBBBBBBBXBBBB',
      '..XBBBBBXXXXXXXXXXXXBBBB',
      '..XBBBBB............BBBB',
      '..XAAAAA............AAAA',
      '...XXXXXX......XXXXXX...',
      '....XBBBBX....XBBBBX....',
      '....XBBBBX....XBBBBX....',
      '....XBBBBX....XBBBBX....',
      '....XXXXXX....XXXXXX....',
      '........................',
      '........................',
      '........................',
    ],
  },
  aegisox: {
    child: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '.......A..A..A.A........',
      '........XBBBBBB.........',
      '........XBBBBBB.........',
      '........BBBBBBBX........',
      '.......BBBBBBBBBX.......',
      '......XLLLLLLLLLL.......',
      '......XBBBBBBBBBB.......',
      '......XX.X...X.X........',
      '......XX.X...X.X........',
      '......XX.X...X.X........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teen: [
      '........................',
      '........................',
      '........................',
      '......A..A....A.AA......',
      '.......XXXXXXXXX........',
      '.......BBBBBBBBBX.......',
      '.......BBBPBBPBBX.......',
      '.......XXBBBBBBXX.......',
      '......XBBBBBBBBBBX......',
      '.....XBBBBBBBBBBBBX.....',
      '....BBBBBBBBBBBBBBBX....',
      '....LLLLLLLLLLLLLLLX....',
      '....LLLLLLLLLLLLLLLX....',
      '....XXXXXXXXXXXXXXXX....',
      '....XX.XX....XX.XXX.....',
      '....XX.XX....XX.XXX.....',
      '....XX.XX....XX.XXX.....',
      '....XX.XX....XX.XXX.....',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    adult: [
      '....AA..A......A..AA....',
      '...AA...AA....AA...AA...',
      '......XXXXXXXXXXXX......',
      '.....XBBBBBBBBBBBBX.....',
      '.....XBBBEPBBEPBBBX.....',
      '.....XBBBBBBBBBBBBX.....',
      '.....XXXBBBBBBBBXXX.....',
      '....XBBBBBBBBBBBBBBX....',
      '...XBBBBBBBBBBBBBBBBX...',
      '..XBBBBBBBBBBBBBBBBBBX..',
      '.XBBBBBBBBBBBBBBBBBBBBX.',
      '.XLLLLLLLLLLLLLLLLLLLLX.',
      '.XLLLLLLLLLLLLLLLLLLLLX.',
      '.XBBBBBBBBBBBBBBBBBBBBX.',
      '.XXXXXXXXXXXXXXXXXXXXXX.',
      '.XXX..XX......XX..XXX...',
      '.XXX..XX......XX..XXX...',
      '.XXX..XX......XX..XXX...',
      '.XXX..XX......XX..XXX...',
      '.XXX..XX......XX..XXX...',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  maneleo: {
    child: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........A...AA..........',
      '.......AAXXXXAAA........',
      '.......ABEBEBXA.........',
      '........XXXXA...........',
      '........BBBBBBBXA.......',
      '.......BBBBBBBBBX.......',
      '......XLLLLLLLLLL.......',
      '......XXXXXXXXXXX.......',
      '......XX.X..X.XX........',
      '......XX.X..X.XX........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teen: [
      '........................',
      '........................',
      '........................',
      '.......AA.AA............',
      '.....AAA......AAA.......',
      '....AAAAXXXXXXAAAA......',
      '....AAABBBBBBBBXAA......',
      '.....AAXXXXXXXAA........',
      '......AXXXXXX...........',
      '.......XXXXXX...AA......',
      '.....XBBBBBBBBBBBBX.....',
      '....XBBBBBBBBBBBBBB.....',
      '....BBBBBBBBBBBBBBBX....',
      '....BBBBBBBBBBBBBBBX....',
      '....XXXXXXXXXXXXXXXX....',
      '....XX..XX..X...XX......',
      '....XX..XX..X...XX......',
      '....XX..XX..X...XX......',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    adult: [
      '......AA..AA............',
      '....AAA......AAA........',
      '...AAAA........AAAA.....',
      '..AAAAAXXXXXXXXAAAAA....',
      '..AAAXBBBBBBBBBBXAAA....',
      '..AAXBBEPBBEPBBXAA......',
      '...AAXXXXXXXXXXAA.......',
      '....AXXXXXXXXA..........',
      '......XXXXXXXX...AAA....',
      '....XBBBBBBBBBBBBBBX.AA.',
      '...XBBBBBBBBBBBBBBBBX...',
      '..XBBBBBBBBBBBBBBBBBBX..',
      '.XBBBBBBBBBBBBBBBBBBBBX.',
      '.XLLLLLLLLLLLLLLLLLLLLX.',
      '.XBBBBBBBBBBBBBBBBBBBBX.',
      '.XXXXXXXXXXXXXXXXXXXXXX.',
      '.XXX...XX...XX...XXX....',
      '.XXX...XX...XX...XXX....',
      '.XXX...XX...XX...XXX....',
      '.XXX...XX...XX...XXX....',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  grivvel: {
    child: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '.......X.X..............',
      '......XXXX..............',
      '......BBBBX.............',
      '......XAAAAAAAAAA.......',
      '......BBAAAAAAAABX......',
      '......BBBBBBBBBBBX......',
      '......XXXXXXXXXXX.......',
      '......X.X....X.XAA......',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teen: [
      '........................',
      '........................',
      '........................',
      '........................',
      '....BBXBX...............',
      '....XXXXXX..............',
      '....BEPEPB..............',
      '...XBBBBXX..............',
      '....AAAAAAAAAAAAAAAX....',
      '...XAAAAAAAAAAAAAAAAX...',
      '...XBBAAAAAAAAAAAABBX...',
      '...XBBBBBBBBBBBBBBBBX...',
      '...XBBBBBBBBBBBBBBBBX...',
      '....X..X......XX.XXAA...',
      '....X..X......XX.XXAA...',
      '....X........X...AAAA...',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    adult: [
      '........................',
      '..XX..XX................',
      '.XBBXBBX................',
      '.XXXXXXXX...............',
      '.BBEPBEPBX..............',
      'XBBBBBBBBX..............',
      'XBBBBBBXXX..............',
      '.XAAAAAAAAAAAAAAAAAAAAX.',
      'XAAAAAAAAAAAAAAAAAAAAAAX',
      'XBBBAAAAAAAAAAAAAAAABBBX',
      'XBBBAAAAAAAAAAAAAAAABBBX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      '.XXXXXXXXXXXXXXXXXXXXXX.',
      '.XX..XX........XX..XXAAA',
      '.XX..XX........XX..XXAAA',
      '..X..X........X..X.AAAAA',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  ursath: {
    child: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........XB....XB........',
      '........XBBBBBB.........',
      '........XXXXXXX.........',
      '.......BBBBBBBBBBX......',
      '......XXXXXXXXXXXX......',
      '......BBBBBBBBBBBX......',
      '......LLLLLLLLLLLX......',
      '......XXXXXXXXXXXX......',
      '......X..X..X..X........',
      '......X..X.X..X.........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teen: [
      '........................',
      '........................',
      '........................',
      '.......XX......X........',
      '.......XXXXXXXX.........',
      '.......BBBBBBBBBX.......',
      '......XBBEBBEBBB........',
      '.....XBBBXXXXXXX........',
      '....XBBBBBBBBBBBBBBBX...',
      '....BBBBBBBBBBBBBBBBB...',
      '...XBBBBBBBBBBBBBBBBX...',
      '...XBBBBBBBBBBBBBBBBX...',
      '...XBBBBBBBBBBBBBBBBX...',
      '...XBBBBBBBBBBBBBBBBX...',
      '...XXXXXXXXXXXXXXXXXX...',
      '...XX..XXX..XX..XXX.....',
      '...XX..XXX..XX..XXX.....',
      '....X..XX..XX..X........',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    adult: [
      '......XX........XX......',
      '.....XBBX........XBBX...',
      '......XXXXXXXXXX........',
      '.....XBBBBBBBBBBBBX.....',
      '....XBBBEPBBEPBBBX......',
      '....XXXXXXXXXXXXXX......',
      '...XBBBBXXXXXXXXXX......',
      '..XBBBBBBBBBBBBBBBBBBBBX',
      '.XBBBBBBBBBBBBBBBBBBBBBB',
      '.XXXXXXXXXXXXXXXXXXXXXXX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      'XLLLLLLLLLLLLLLLLLLLLLLX',
      'XBBBBBBBBBBBBBBBBBBBBBBX',
      'XXXXXXXXXXXXXXXXXXXXXXXX',
      'XXX...XXX...XXX...XXX...',
      'XXX...XXX...XXX...XXX...',
      'XXX...XXX...XXX...XXX...',
      '.XX...XX...XX...XX......',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
}

// Per-species real colour palette (overrides the generic hue-rotated
// palette() from sprites.ts for any species with an entry here).
export const SPECIES_PALETTE: Partial<Record<string, Record<string, string>>> = {
  kongrath: {"X":"#141212","B":"#2b2b2e","L":"#a8a5a0","A":"#8a8580","E":"#f4f4f8","P":"#0c0d10"},
  aegisox: {"X":"#3d2a1e","B":"#8a6b4f","L":"#c9ab84","A":"#efe6d3","E":"#f4f4f8","P":"#0c0d10"},
  maneleo: {"X":"#5c3a1a","B":"#dcab48","L":"#f0d9a0","A":"#a85a1e","E":"#f4f4f8","P":"#0c0d10"},
  grivvel: {"X":"#100d0a","B":"#3c2b20","L":"#c9a15f","A":"#1a1512","E":"#f4f4f8","P":"#0c0d10"},
  ursath: {"X":"#3a2515","B":"#8c5a34","L":"#d9b58a","A":"#6e4527","E":"#f4f4f8","P":"#0c0d10"},
}
